### ISSUE TITLE
yuva420p(alpha channel) support for yuva420p.webp/webm

### ISSUE THREAD

**Issue by enctac** [HolyWu/L-SMASH-Works#6]
Sorry,I'm not good at English.

alphachannel.webp has yuva420p(yuv420p with alpha channnel) format.

sample:

  https://www.gstatic.com/webp/gallery3/1_webp_a.webp
  ( from: https://developers.google.com/speed/webp/gallery2?hl=ja )

I've made patch #5 to add yuva420p support for AviUtl.
[This seems to work fine](https://user-images.githubusercontent.com/30576569/77389376-600b3e80-6dd6-11ea-9dbc-eba495cc1078.jpg). (AviUtl + exedit plugin)
But I don't know how to add yuva420p support for Avisynth/Vapoursynth.

Please add yuva420p support for Avisynth/Vapoursynth.

P.S.
Also VP8_VP9_with_alpha_channnel.webm has alpha channel.
~~But ffprobe says this is yuv420p format.(not yuva420p)
I don't know why.Any Information?
(ffmpeg can't decode VP8_VP9_with_alpha_channnel.webm as yuva420p?)~~
edit:
  ffmpeg can decode VP8_VP9_with_alpha_channnel.webm as yuva420p when using libvpx,libvpx-vp9 decoder.
  But specifying "libvpx,libvpx-vp9" to "Prefferd decoders"(AviUtl), L-SMASH Works treat VP8_VP9_with_alpha_channnel.webm as yuv420p. (not yuva420p)
  I don't know why...

sample:
  https://simpl.info/videoalpha/video/dancer1.webm
  (from:
    https://developers.google.com/web/updates/2013/07/Alpha-transparency-in-Chrome-video
    https://simpl.info/videoalpha/ )

**Comment by enctac** [comment]
I noticed the following:

L-SMASH Works -> r1036 + #5 (with libvpx) 

1. When decoder=libvpx:
If dancer1.webm.lwi is not exist, L-SMASH Works treat dancer1.webm as yuva420p.
But if dancer1.webm.lwi is exist, L-SMASH Works treat dancer1.webm as yuv420p.

2. When decoder=libvpx, and dancer1.webm.lwi is not exist:
Format information in generated dancer1.webm.lwi is below.
StreamInfo : yuv420p
ExtraDataList : yuva420p  (<- alpha channel)

3. When decoder=vp8, and dancer1.webm.lwi is not exist:
Format information in generated dancer1.webm.lwi is below.
StreamInfo : yuv420p
ExtraDataList : yuv420p

**Comment by HolyWu** [comment]
Added in https://github.com/HolyWu/L-SMASH-Works/commit/e3e284a63227410a498aa464f46bfb49586d4a55 and https://github.com/HolyWu/L-SMASH-Works/commit/4bd95da8a7a64baaa888f058b15e056deab66c18.
